### ISSUE TITLE
people switching Airplane mode in ios,Server does not listen to disconnect

### ISSUE THREAD

**Issue by yumin5723** [morozovsk/websocket-examples#4]
hello,i use you project to build a chat ios app,but people switching Airplane mode in ios,Server does not listen to disconnect，so server also sendToClient , then the message is lost.how did i resolve this? thank you

**Comment by morozovsk** [comment]
Hello. This is standart behavior for linux socket. Linux system try to send tcp control packet every 15 minutes into connection 5 or 6 times. If system does not receive control answer, then system close connection. For flexible settings you can use nginx proxy configuration. For example: https://github.com/morozovsk/websocket/wiki/Together-with-nginx

**Comment by yumin5723** [comment]
let me try,thank you very much
