### ISSUE TITLE
autoload.php

### ISSUE THREAD

**Issue by malofan** [morozovsk/websocket-examples#5]
Доброго времени суток!
не могу понять строчки: require_once **DIR** . '/../../../../autoload.php';
в каждом из индексных файлов...
что должно быть в этом скрипте?
Спасибо за ответ!

**Comment by morozovsk** [comment]
файл композера

**Comment by malofan** [comment]
не догадаося.... а если без композера? вопрос на 5, но все же))) не все так прекрасно с моими позниниями, как мне бы того хотелось...

**Comment by Darelsbn** [comment]
Ошибка в строке $WebsocketServer = new morozovsk\websocket\Server($config);

Консоль: Fatal error: Uncaught Error: Class 'morozovsk\websocket\Server' not found in C:\OpenServer\domains\morozovsk\websocket-examples\chat\server\index.php:19
Stack trace:
#0 {main}
  thrown in C:\OpenServer\domains\morozovsk\websocket-examples\chat\server\index.php on line 19

**Comment by morozovsk** [comment]
@Darelsbn под windows не работает
