### ISSUE TITLE
How to launch morozovsk/websocket-examples/chat-2?

### ISSUE THREAD

**Issue by it19862** [morozovsk/websocket-examples#6]
I want to try chat 2.

**Completed.**
      - Created the project folder. c:\project\websocketChat2;
      - Opened the console Open Server;
      - CD c:\project\websocketChat2;
      - composer needs morozovsk/websocket-examples;
      - next, see the pictures.

**Question:** What to do next?

**I use.**
- Windows -10x64;
- Openserver;

![14 06 2022_23-56-19](https://user-images.githubusercontent.com/18245828/173756284-dc581444-9d6c-4078-ae41-ab7278c7c6e7.png)

**Comment by morozovsk** [comment]
>This library works, but I will not develop and support it because I will use https://github.com/walkor/Workerman
